game_names = {100: "THE ARTIFICIAL",
              101: "FRIEDRICH II",
              102: "Two Sides",
              103: "PNEUMOCONIOSIS",
              104: "DEVASTATORS",
              106: "MERRY CHRISTMAS",
              107: "TRIPLICATION",
              108: "FUNERAL MARCH",
              109: "INTERGLACIAL",
              110: "Templar Knights",
              111: "JAUNTIER TREESOME",
              112: "Stars n Stripes",
              113: "All VS ME !",
              114: "ACCOUNTING EQUATION",
              116: "Citykiller",
              117: "FOUR POWER TALKS",
              118: "Rushhour",
              119: "CONTRADISTINCTION",
              120: "SALIVATION",
              122: "Hexenkessel",
              123: "AIRFIGHT",
              125: "SWARTHINESS",
              126: "CRYOGENICS",
              128: "The Last Stand",
              130: "Run To The Hills",
              131: "Shootout",
              132: "UNDER THE GUN",
              133: "Terror",
              134: "BLITZKRIEG",
              140: "Kreuzberg",
              141: "Let's kick E.T.'s A**!",
              142: "Clashing",
              143: "Fort Bravo",
              144: "Sarlacc Pit",
              145: "Dogfight",
              146: "Outback",
              147: "CryBaby",
              149: "JAZZ",
              80: "NET 4 2",
              81: "THE NET ON HILL",
              82: "Easy-Net",
              83: "ROBOT",
              84: "STEAMHAMMER",
              85: "Kleine Netzigkeit",
              86: "GET OUT OF MY WAY",
              87: "The Race",
              88: "Netropolis",
              89: "CROSS OVER",
              90: "North or South",
              91: "THERE CAN ONLY BE ONE",
              92: "Powerplant",
              93: "13",
              95: "Lost and Found",
              96: "DUO",
              }
